# API Endpoint paths:
API = "/api"
STACK = "/stack"
COMPONENT = "/component"
SESSION = "/session"
EMBEDDING = "/embedding"
RETRIEVER = "/retriever"
VECTORDB = "/vectordb"
ETL = "/etl"
PROMPT_ENGINE = "/prompt-engine"
MODEL = "/model"
