# API Endpoint paths:
API = "/api"
STACK = "/stack"
COMPONENT = "/component"
SESSION = "/session"
RETRIEVER = "/retriever"
VECTORDB = "/vectordb"
ETL = "/etl"
PROMPT_ENGINE = "/prompt-engine"
LLM_CACHE = "/llm-cache"
MODEL = "/model"
