"""Add prompts table

Revision ID: 7dd5490b4f14
Revises: f5cbe001454d
Create Date: 2023-10-05 08:58:16.091864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd5490b4f14'
down_revision: Union[str, None] = 'f5cbe001454d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stack_session', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SIMPLE_CHAT_PROMPT', 'CONTEXTUAL_CHAT_PROMPT', 'CONTEXTUAL_QA_PROMPT', name='prompttypeenum'), nullable=True),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stack_session'], ['stack_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompts')
    # ### end Alembic commands ###
