{
    "components":{
        "vectordb":{
            "name":"chromadb",
            "config":{}
        },
        "memory":{
            "name":"langchain",
            "config":{}
        },
        "llm_cache":{
            "name":"cache",
            "config":{}
        },
        "model":{
            "name":"gpt3.5",
            "config":{}
        },
        "embedding":{
            "name":"langchain",
            "config":{}
        },
        "retriever":{
            "name":"langchain",
            "config":{}
        }
    }
}
